baseURL = "https://yehzu.github.io/"
languageCode = "en-us"
title = "å°è‘‰éš¨ç­†"
theme = "PaperMod"

[params]
    defaultTheme = "light" # auto, light, dark
    description = "There is no try."
    author = "yehzu"

    [params.homeInfoParams]
        Title = "Hi there ğŸ‘‹"
        Content = "Welcome to my blog."

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/yehzu"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/yehzu/"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30